### ISSUE TITLE
&i32 uninitialized

### ISSUE THREAD

**Issue by pretzel729** [alborrajo/sheetesia#4]
I managed to get sheetesia installed, however I keep getting "attempted to leave type `&i32` uninitialized, which is invalid".
I'm a bit unsure if the problem is the video I used as input or my install.
Do you have a link to a synthesia YouTube video that is known to work?

``` 
   Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/sheetesia /home/sheetesia/Downloads/test.mp4`
Loaded video: /home/sheetesia/Downloads/test.mp4
Finding piano...
thread 'main' panicked at 'attempted to leave type `&i32` uninitialized, which is invalid', /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/mem/mod.rs:664:9
stack backtrace:
   0:     0x5589bc24e945 - backtrace::backtrace::libunwind::trace::h14d338b30b3ea0a7
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x5589bc24e945 - backtrace::backtrace::trace_unsynchronized::h73ea91d74a3fd67f
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x5589bc24e945 - std::sys_common::backtrace::_print_fmt::hd42948c952866e12
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5589bc24e945 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha8f928866ff7571e
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5589bc27098c - core::fmt::write::he0c1e5f7426d2718
                               at src/libcore/fmt/mod.rs:1076
   5:     0x5589bc24cce2 - std::io::Write::write_fmt::hf3afc6cfd57d0033
                               at src/libstd/io/mod.rs:1537
   6:     0x5589bc250dd0 - std::sys_common::backtrace::_print::hfc0110703f3696fd
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5589bc250dd0 - std::sys_common::backtrace::print::h3f77c6990ddfaa22
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5589bc250dd0 - std::panicking::default_hook::{{closure}}::heae49580a8d62d75
                               at src/libstd/panicking.rs:198
   9:     0x5589bc250b1c - std::panicking::default_hook::hecc34e3f729e213c
                               at src/libstd/panicking.rs:217
  10:     0x5589bc251413 - std::panicking::rust_panic_with_hook::he82f5d0644692441
                               at src/libstd/panicking.rs:526
  11:     0x5589bc25100b - rust_begin_unwind
                               at src/libstd/panicking.rs:437
  12:     0x5589bc26f321 - core::panicking::panic_fmt::h09c929f06bb87c98
                               at src/libcore/panicking.rs:85
  13:     0x5589bc26f26d - core::panicking::panic::h7ece43057e5422d4
                               at src/libcore/panicking.rs:50
  14:     0x5589bc22135d - core::mem::uninitialized::h31ccf8f63b6b19f4
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/mem/mod.rs:664
  15:     0x5589bc22135d - opencv::manual::core::mat::<impl core::ops::deref::Deref for opencv::opencv::hub::core::MatSize>::deref::hec635c92054c95aa
                               at /home/sheetesia/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.19.1/src/manual/core/mat.rs:483
  16:     0x5589bc220c3a - opencv::manual::core::mat::<impl opencv::opencv::hub::core::Mat>::match_indices::h3a55c63919785bcc
                               at /home/sheetesia/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.19.1/src/manual/core/mat.rs:135
  17:     0x5589bc1fe0ec - opencv::manual::core::mat::<impl opencv::opencv::hub::core::Mat>::_at_2d::{{closure}}::h866e45068683c277
                               at /home/sheetesia/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.19.1/src/manual/core/mat.rs:223
  18:     0x5589bc1fc0a5 - core::result::Result<T,E>::and_then::h6054b60a715c0b5d
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/result.rs:729
  19:     0x5589bc20387e - opencv::manual::core::mat::<impl opencv::opencv::hub::core::Mat>::_at_2d::he5c592704597ae5e
                               at /home/sheetesia/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.19.1/src/manual/core/mat.rs:222
  20:     0x5589bc20387e - opencv::opencv::hub::core::Mat::at_2d::h9308e158f153a758
                               at /home/sheetesia/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.19.1/src/opencv/hub/core.rs:6132
  21:     0x5589bc2084e2 - sheetesia::piano::octave::Octave::new::h0da03a5d99770641
                               at src/piano/octave.rs:33
  22:     0x5589bc206a7e - sheetesia::piano::piano::Piano::new::hb8c6b7c5fd6a4b20
                               at src/piano/piano.rs:62
  23:     0x5589bc20a489 - sheetesia::main::h0c203e511dd4adf8
                               at src/main.rs:37
  24:     0x5589bc205e2b - std::rt::lang_start::{{closure}}::hbc293255acb6abc8
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
  25:     0x5589bc2517e3 - std::rt::lang_start_internal::{{closure}}::h5d3ea623498f5f43
                               at src/libstd/rt.rs:52
  26:     0x5589bc2517e3 - std::panicking::try::do_call::hac65e71be769a440
                               at src/libstd/panicking.rs:348
  27:     0x5589bc2517e3 - std::panicking::try::hd4706e264bcf6712
                               at src/libstd/panicking.rs:325
  28:     0x5589bc2517e3 - std::panic::catch_unwind::h948a0fb4a8b3ee82
                               at src/libstd/panic.rs:394
  29:     0x5589bc2517e3 - std::rt::lang_start_internal::h72cc068ed2d0ac53
                               at src/libstd/rt.rs:51
  30:     0x5589bc205e07 - std::rt::lang_start::h1c1b4d114fbe39b4
                               at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
  31:     0x5589bc20c01a - main
  32:     0x7fbd740e1b97 - __libc_start_main
  33:     0x5589bc1f9eba - _start
  34:                0x0 - <unknown>
```

**Comment by alborrajo** [comment]
The program looks for the piano on the video on the first frame, therefore, the video must start with the piano visible on the first frame. 
[megalovania.mp4.zip](https://github.com/alborrajo/sheetesia/files/5291377/megalovania.mp4.zip)
Try with this video

**Comment by jivimberg** [comment]
I'm running into a similar error even with the provided megalovania video

```
Loaded video: /Users/jvimberg/Downloads/megalovania.mp4
Finding piano...
thread 'main' panicked at 'attempted to leave type `&i32` uninitialized, which is invalid', /Users/jvimberg/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/mem/mod.rs:659:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
   3: core::mem::uninitialized
             at /Users/jvimberg/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/mem/mod.rs:659:9
   4: opencv::manual::core::mat::<impl core::ops::deref::Deref for opencv::opencv::hub::core::MatSize>::deref
             at /Users/jvimberg/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.19.1/src/manual/core/mat.rs:483:19
   5: opencv::manual::core::mat::<impl opencv::opencv::hub::core::Mat>::match_indices
             at /Users/jvimberg/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.19.1/src/manual/core/mat.rs:135:33
   6: opencv::manual::core::mat::<impl opencv::opencv::hub::core::Mat>::_at_2d::{{closure}}
             at /Users/jvimberg/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.19.1/src/manual/core/mat.rs:223:27
   7: core::result::Result<T,E>::and_then
             at /Users/jvimberg/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:708:22
   8: opencv::manual::core::mat::<impl opencv::opencv::hub::core::Mat>::_at_2d
             at /Users/jvimberg/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.19.1/src/manual/core/mat.rs:222:9
   9: opencv::opencv::hub::core::Mat::at_2d
             at /Users/jvimberg/.cargo/registry/src/github.com-1ecc6299db9ec823/opencv-0.19.1/src/opencv/hub/core.rs:6132:80
  10: sheetesia::piano::octave::Octave::new
             at ./src/piano/octave.rs:33:44
  11: sheetesia::piano::piano::Piano::new
             at ./src/piano/piano.rs:62:18
  12: sheetesia::main
             at ./src/main.rs:37:25
  13: core::ops::function::FnOnce::call_once
             at /Users/jvimberg/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The line is not exactly the same as the one reported by @pretzel729

**Comment by alborrajo** [comment]
Hi, sorry for the late answer, i just pushed a commit updating to the latest version of the opencv dependency and managed to get it running without any issues.
Could you please try again with the latest commit? If you have any issues let me know.
